FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Installer Python + pip + setuptools
RUN dnf update -y && \
    dnf install -y python3 python3-pip python3-setuptools && \
    dnf clean all

WORKDIR /app

# Mettre à jour pip
RUN pip3 install --upgrade pip setuptools wheel

# Installer dépendances
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copier code source
COPY . .

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
