FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Installer Python, pip, wheel et setuptools via dnf
RUN dnf update -y && \
    dnf install -y python3 python3-pip python3-setuptools python3-wheel && \
    dnf clean all

WORKDIR /app

# Installer dépendances Python
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt

# Copier code source
COPY . .

EXPOSE 8000

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
